create extension if not exists "pgjwt" with schema "extensions";

create type "public"."document_status" as enum ('pending', 'processing', 'completed', 'failed');

create type "public"."job_status" as enum ('pending', 'processing', 'ready', 'matching', 'completed', 'failed');

create type "public"."match_decision" as enum ('rejected', 'accepted', 'pending');


  create table "public"."accepted_matches" (
    "id" bigint generated by default as identity not null,
    "term" text,
    "recommended_choice" uuid,
    "accepted_project" uuid,
    "user_id" uuid,
    "created_at" timestamp with time zone not null default now(),
    "intern_id" uuid
      );


alter table "public"."accepted_matches" enable row level security;


  create table "public"."jobs" (
    "id" uuid not null default gen_random_uuid(),
    "term" text,
    "status" public.job_status not null default 'pending'::public.job_status,
    "created_at" timestamp with time zone default now(),
    "rust_error" jsonb default '{"resumes": [], "projects": []}'::jsonb,
    "python_error" text
      );


alter table "public"."jobs" enable row level security;


  create table "public"."matches" (
    "id" uuid not null default gen_random_uuid(),
    "match_batch_id" uuid default gen_random_uuid(),
    "term" text,
    "intern_id" uuid,
    "project_id" uuid,
    "similarity_score" double precision,
    "created_at" timestamp with time zone not null,
    "decision" public.match_decision not null default 'pending'::public.match_decision
      );


alter table "public"."matches" enable row level security;


  create table "public"."project_uploads" (
    "id" uuid not null default gen_random_uuid(),
    "filename" text not null,
    "status" public.document_status not null default 'pending'::public.document_status,
    "error_message" text,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "term" text,
    "job_id" uuid
      );


alter table "public"."project_uploads" enable row level security;


  create table "public"."projects" (
    "id" uuid not null default gen_random_uuid(),
    "upload_id" uuid,
    "title" text not null,
    "description" text,
    "requirements" text,
    "manager" text,
    "deadline" text,
    "priority" smallint default 0,
    "intern_cap" smallint default 1,
    "created_at" timestamp with time zone not null default now(),
    "term" text,
    "deliverable" text
      );


alter table "public"."projects" enable row level security;


  create table "public"."results" (
    "id" uuid not null default gen_random_uuid(),
    "term" text not null,
    "match_id" uuid not null,
    "intern_id" character varying,
    "Third_Score" real,
    "recommended_project_id" uuid default gen_random_uuid(),
    "status" character varying default 'pending'::character varying,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."results" enable row level security;


  create table "public"."results_tab" (
    "id" uuid not null default gen_random_uuid(),
    "match_id" uuid not null,
    "term" text not null,
    "intern_id" uuid not null,
    "projects" jsonb not null,
    "recommended_project_id" uuid,
    "status" text not null default 'pending'::text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."results_tab" enable row level security;


  create table "public"."resume_uploads" (
    "id" uuid not null default gen_random_uuid(),
    "filename" text not null,
    "status" public.document_status not null default 'pending'::public.document_status,
    "error_message" text,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "term" text,
    "zip_id" uuid,
    "job_id" uuid
      );


alter table "public"."resume_uploads" enable row level security;


  create table "public"."resumes" (
    "filename" text not null,
    "text" text,
    "structured" json,
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "created_at" timestamp with time zone default now(),
    "zip_id" uuid,
    "term" text,
    "upload_id" uuid
      );


alter table "public"."resumes" enable row level security;


  create table "public"."zip_archives" (
    "id" uuid not null default gen_random_uuid(),
    "filename" text not null,
    "status" public.document_status not null default 'pending'::public.document_status,
    "error_message" text,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid,
    "term" text,
    "job_id" uuid
      );


alter table "public"."zip_archives" enable row level security;

CREATE UNIQUE INDEX accepted_matches_pkey ON public.accepted_matches USING btree (id);

CREATE INDEX idx_projects_upload_id ON public.projects USING btree (upload_id);

CREATE UNIQUE INDEX jobs_pkey ON public.jobs USING btree (id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX project_uploads_pkey ON public.project_uploads USING btree (id);

CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);

CREATE UNIQUE INDEX results_tab_pkey ON public.results_tab USING btree (id);

CREATE UNIQUE INDEX resume_uploads_pkey ON public.resume_uploads USING btree (id);

CREATE UNIQUE INDEX resumes_pkey ON public.resumes USING btree (id);

CREATE UNIQUE INDEX zip_archives_pkey ON public.zip_archives USING btree (id);

alter table "public"."accepted_matches" add constraint "accepted_matches_pkey" PRIMARY KEY using index "accepted_matches_pkey";

alter table "public"."jobs" add constraint "jobs_pkey" PRIMARY KEY using index "jobs_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."project_uploads" add constraint "project_uploads_pkey" PRIMARY KEY using index "project_uploads_pkey";

alter table "public"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "public"."results_tab" add constraint "results_tab_pkey" PRIMARY KEY using index "results_tab_pkey";

alter table "public"."resume_uploads" add constraint "resume_uploads_pkey" PRIMARY KEY using index "resume_uploads_pkey";

alter table "public"."resumes" add constraint "resumes_pkey" PRIMARY KEY using index "resumes_pkey";

alter table "public"."zip_archives" add constraint "zip_archives_pkey" PRIMARY KEY using index "zip_archives_pkey";

alter table "public"."accepted_matches" add constraint "accepted_matches_accepted_project_fkey" FOREIGN KEY (accepted_project) REFERENCES public.projects(id) not valid;

alter table "public"."accepted_matches" validate constraint "accepted_matches_accepted_project_fkey";

alter table "public"."accepted_matches" add constraint "accepted_matches_intern_id_fkey" FOREIGN KEY (intern_id) REFERENCES public.resumes(id) not valid;

alter table "public"."accepted_matches" validate constraint "accepted_matches_intern_id_fkey";

alter table "public"."accepted_matches" add constraint "accepted_matches_recommended_choice_fkey" FOREIGN KEY (recommended_choice) REFERENCES public.projects(id) not valid;

alter table "public"."accepted_matches" validate constraint "accepted_matches_recommended_choice_fkey";

alter table "public"."accepted_matches" add constraint "accepted_matches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."accepted_matches" validate constraint "accepted_matches_user_id_fkey";

alter table "public"."matches" add constraint "matches_intern_id_fkey" FOREIGN KEY (intern_id) REFERENCES public.resumes(id) not valid;

alter table "public"."matches" validate constraint "matches_intern_id_fkey";

alter table "public"."matches" add constraint "matches_project_id_fkey" FOREIGN KEY (project_id) REFERENCES public.projects(id) not valid;

alter table "public"."matches" validate constraint "matches_project_id_fkey";

alter table "public"."project_uploads" add constraint "fk_project_uploads_job" FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL not valid;

alter table "public"."project_uploads" validate constraint "fk_project_uploads_job";

alter table "public"."projects" add constraint "projects_upload_id_fkey" FOREIGN KEY (upload_id) REFERENCES public.project_uploads(id) ON DELETE CASCADE not valid;

alter table "public"."projects" validate constraint "projects_upload_id_fkey";

alter table "public"."resume_uploads" add constraint "fk_resume_uploads_job" FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL not valid;

alter table "public"."resume_uploads" validate constraint "fk_resume_uploads_job";

alter table "public"."resume_uploads" add constraint "resume_uploads_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."resume_uploads" validate constraint "resume_uploads_user_id_fkey";

alter table "public"."resume_uploads" add constraint "resume_uploads_zip_id_fkey" FOREIGN KEY (zip_id) REFERENCES public.zip_archives(id) not valid;

alter table "public"."resume_uploads" validate constraint "resume_uploads_zip_id_fkey";

alter table "public"."resumes" add constraint "resumes_upload_id_fkey" FOREIGN KEY (upload_id) REFERENCES public.resume_uploads(id) ON DELETE SET NULL not valid;

alter table "public"."resumes" validate constraint "resumes_upload_id_fkey";

alter table "public"."resumes" add constraint "resumes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."resumes" validate constraint "resumes_user_id_fkey";

alter table "public"."resumes" add constraint "resumes_zip_id_fkey" FOREIGN KEY (zip_id) REFERENCES public.zip_archives(id) ON DELETE SET NULL not valid;

alter table "public"."resumes" validate constraint "resumes_zip_id_fkey";

alter table "public"."zip_archives" add constraint "fk_zip_archives_job" FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE SET NULL not valid;

alter table "public"."zip_archives" validate constraint "fk_zip_archives_job";

alter table "public"."zip_archives" add constraint "zip_archives_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."zip_archives" validate constraint "zip_archives_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_project_upload()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  job_id_val uuid;
BEGIN
  IF new.bucket_id = 'project-spreadsheets' and new.name NOT LIKE '%.emptyFolderPlaceholder' THEN
    begin
      job_id_val := (new.user_metadata ->> 'job_id')::uuid;
      if job_id_val is null then
         job_id_val := (new.metadata ->> 'job_id')::uuid;
      end if;
    exception when others then
      job_id_val := null;
    end;

    INSERT INTO public.project_uploads (filename, user_id, term, job_id)
    VALUES (
      new.name, 
      new.owner,
      CASE WHEN position('/' in new.name) > 0 THEN split_part(new.name, '/', 1) ELSE NULL END,
      job_id_val
    );
  END IF;
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_resume_upload()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  zip_id_val uuid;
  job_id_val uuid;
begin
  -- Ignore folder placeholders created by Supabase Dashboard
  if new.bucket_id = 'resumes' and new.name NOT LIKE '%.emptyFolderPlaceholder' then
    -- Extract zip_id and job_id from metadata
    begin
      zip_id_val := (new.user_metadata ->> 'zip_id')::uuid;
      if zip_id_val is null then
         zip_id_val := (new.metadata ->> 'zip_id')::uuid;
      end if;
    exception when others then
      zip_id_val := null;
    end;

    begin
      job_id_val := (new.user_metadata ->> 'job_id')::uuid;
      if job_id_val is null then
         job_id_val := (new.metadata ->> 'job_id')::uuid;
      end if;
    exception when others then
      job_id_val := null;
    end;

    -- INSERT INTO resume_uploads
    insert into public.resume_uploads (
      user_id,
      filename,
      term,
      zip_id,
      job_id
    )
    values (
      new.owner,
      new.name,
      CASE WHEN position('/' in new.name) > 0 THEN split_part(new.name, '/', 1) ELSE NULL END,
      zip_id_val,
      job_id_val
    );
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_zip_upload()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  job_id_val uuid;
BEGIN
  IF new.bucket_id = 'zip-archives' and new.name NOT LIKE '%.emptyFolderPlaceholder' THEN
    begin
      job_id_val := (new.user_metadata ->> 'job_id')::uuid;
      if job_id_val is null then
         job_id_val := (new.metadata ->> 'job_id')::uuid;
      end if;
    exception when others then
      job_id_val := null;
    end;

    INSERT INTO public.zip_archives (filename, user_id, term, job_id)
    VALUES (
      new.name, 
      new.owner,
      CASE WHEN position('/' in new.name) > 0 THEN split_part(new.name, '/', 1) ELSE NULL END,
      job_id_val
    );
  END IF;
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_project_deletion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF old.bucket_id = 'project-spreadsheets' THEN
    DELETE FROM public.project_uploads
    WHERE filename = old.name;
  END IF;
  RETURN old;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_resume_deletion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
  -- 1. Filter: Only run this if the deleted file was in the 'resumes' bucket
  if old.bucket_id = 'resumes' then
  
    -- 2. Delete the row where the file path matches
    delete from public.resumes
    where filename = old.name;
    
  end if;

  return old;
end;$function$
;

CREATE OR REPLACE FUNCTION public.handle_zip_deletion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Check if the deleted file is in the 'zip-archives' bucket
  IF old.bucket_id = 'zip-archives' THEN
    DELETE FROM public.zip_archives
    WHERE filename = old.name;
  END IF;
  RETURN old;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_orchestrator_secure()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  secret text;
  token text;
  url text := TG_ARGV[0];
  headers jsonb;
  request_id bigint;
  payload jsonb;
  timeout_ms integer := 5000;
BEGIN
  -- Get Secret
  SELECT decrypted_secret INTO secret
  FROM vault.decrypted_secrets
  WHERE name = 'app_jwt_secret';

  IF secret IS NULL THEN
    RAISE EXCEPTION 'app_jwt_secret not found in vault';
  END IF;

  -- Sign Token (exp cast to bigint)
  token := sign(
    json_build_object(
      'role', 'service_role',
      'iss', 'supabase',
      'exp', (extract(epoch from now()) + 3600)::bigint,
      'sub', 'orchestrator'
    ),
    secret
  );

  -- Build Headers
  headers := jsonb_build_object(
    'Content-Type', 'application/json',
    'Authorization', 'Bearer ' || token
  );

  -- Build Payload
  payload := jsonb_build_object(
    'old_record', OLD,
    'record', NEW,
    'type', TG_OP,
    'table', TG_TABLE_NAME,
    'schema', TG_TABLE_SCHEMA
  );

  -- Send Request
  SELECT http_post INTO request_id
  FROM net.http_post(
    url,
    payload,
    '{}'::jsonb,
    headers,
    timeout_ms
  );

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."accepted_matches" to "anon";

grant insert on table "public"."accepted_matches" to "anon";

grant references on table "public"."accepted_matches" to "anon";

grant select on table "public"."accepted_matches" to "anon";

grant trigger on table "public"."accepted_matches" to "anon";

grant truncate on table "public"."accepted_matches" to "anon";

grant update on table "public"."accepted_matches" to "anon";

grant delete on table "public"."accepted_matches" to "authenticated";

grant insert on table "public"."accepted_matches" to "authenticated";

grant references on table "public"."accepted_matches" to "authenticated";

grant select on table "public"."accepted_matches" to "authenticated";

grant trigger on table "public"."accepted_matches" to "authenticated";

grant truncate on table "public"."accepted_matches" to "authenticated";

grant update on table "public"."accepted_matches" to "authenticated";

grant delete on table "public"."accepted_matches" to "service_role";

grant insert on table "public"."accepted_matches" to "service_role";

grant references on table "public"."accepted_matches" to "service_role";

grant select on table "public"."accepted_matches" to "service_role";

grant trigger on table "public"."accepted_matches" to "service_role";

grant truncate on table "public"."accepted_matches" to "service_role";

grant update on table "public"."accepted_matches" to "service_role";

grant delete on table "public"."jobs" to "anon";

grant insert on table "public"."jobs" to "anon";

grant references on table "public"."jobs" to "anon";

grant select on table "public"."jobs" to "anon";

grant trigger on table "public"."jobs" to "anon";

grant truncate on table "public"."jobs" to "anon";

grant update on table "public"."jobs" to "anon";

grant delete on table "public"."jobs" to "authenticated";

grant insert on table "public"."jobs" to "authenticated";

grant references on table "public"."jobs" to "authenticated";

grant select on table "public"."jobs" to "authenticated";

grant trigger on table "public"."jobs" to "authenticated";

grant truncate on table "public"."jobs" to "authenticated";

grant update on table "public"."jobs" to "authenticated";

grant delete on table "public"."jobs" to "service_role";

grant insert on table "public"."jobs" to "service_role";

grant references on table "public"."jobs" to "service_role";

grant select on table "public"."jobs" to "service_role";

grant trigger on table "public"."jobs" to "service_role";

grant truncate on table "public"."jobs" to "service_role";

grant update on table "public"."jobs" to "service_role";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."project_uploads" to "anon";

grant insert on table "public"."project_uploads" to "anon";

grant references on table "public"."project_uploads" to "anon";

grant select on table "public"."project_uploads" to "anon";

grant trigger on table "public"."project_uploads" to "anon";

grant truncate on table "public"."project_uploads" to "anon";

grant update on table "public"."project_uploads" to "anon";

grant delete on table "public"."project_uploads" to "authenticated";

grant insert on table "public"."project_uploads" to "authenticated";

grant references on table "public"."project_uploads" to "authenticated";

grant select on table "public"."project_uploads" to "authenticated";

grant trigger on table "public"."project_uploads" to "authenticated";

grant truncate on table "public"."project_uploads" to "authenticated";

grant update on table "public"."project_uploads" to "authenticated";

grant delete on table "public"."project_uploads" to "service_role";

grant insert on table "public"."project_uploads" to "service_role";

grant references on table "public"."project_uploads" to "service_role";

grant select on table "public"."project_uploads" to "service_role";

grant trigger on table "public"."project_uploads" to "service_role";

grant truncate on table "public"."project_uploads" to "service_role";

grant update on table "public"."project_uploads" to "service_role";

grant delete on table "public"."projects" to "anon";

grant insert on table "public"."projects" to "anon";

grant references on table "public"."projects" to "anon";

grant select on table "public"."projects" to "anon";

grant trigger on table "public"."projects" to "anon";

grant truncate on table "public"."projects" to "anon";

grant update on table "public"."projects" to "anon";

grant delete on table "public"."projects" to "authenticated";

grant insert on table "public"."projects" to "authenticated";

grant references on table "public"."projects" to "authenticated";

grant select on table "public"."projects" to "authenticated";

grant trigger on table "public"."projects" to "authenticated";

grant truncate on table "public"."projects" to "authenticated";

grant update on table "public"."projects" to "authenticated";

grant delete on table "public"."projects" to "service_role";

grant insert on table "public"."projects" to "service_role";

grant references on table "public"."projects" to "service_role";

grant select on table "public"."projects" to "service_role";

grant trigger on table "public"."projects" to "service_role";

grant truncate on table "public"."projects" to "service_role";

grant update on table "public"."projects" to "service_role";

grant delete on table "public"."results" to "anon";

grant insert on table "public"."results" to "anon";

grant references on table "public"."results" to "anon";

grant select on table "public"."results" to "anon";

grant trigger on table "public"."results" to "anon";

grant truncate on table "public"."results" to "anon";

grant update on table "public"."results" to "anon";

grant delete on table "public"."results" to "authenticated";

grant insert on table "public"."results" to "authenticated";

grant references on table "public"."results" to "authenticated";

grant select on table "public"."results" to "authenticated";

grant trigger on table "public"."results" to "authenticated";

grant truncate on table "public"."results" to "authenticated";

grant update on table "public"."results" to "authenticated";

grant delete on table "public"."results" to "service_role";

grant insert on table "public"."results" to "service_role";

grant references on table "public"."results" to "service_role";

grant select on table "public"."results" to "service_role";

grant trigger on table "public"."results" to "service_role";

grant truncate on table "public"."results" to "service_role";

grant update on table "public"."results" to "service_role";

grant delete on table "public"."results_tab" to "anon";

grant insert on table "public"."results_tab" to "anon";

grant references on table "public"."results_tab" to "anon";

grant select on table "public"."results_tab" to "anon";

grant trigger on table "public"."results_tab" to "anon";

grant truncate on table "public"."results_tab" to "anon";

grant update on table "public"."results_tab" to "anon";

grant delete on table "public"."results_tab" to "authenticated";

grant insert on table "public"."results_tab" to "authenticated";

grant references on table "public"."results_tab" to "authenticated";

grant select on table "public"."results_tab" to "authenticated";

grant trigger on table "public"."results_tab" to "authenticated";

grant truncate on table "public"."results_tab" to "authenticated";

grant update on table "public"."results_tab" to "authenticated";

grant delete on table "public"."results_tab" to "service_role";

grant insert on table "public"."results_tab" to "service_role";

grant references on table "public"."results_tab" to "service_role";

grant select on table "public"."results_tab" to "service_role";

grant trigger on table "public"."results_tab" to "service_role";

grant truncate on table "public"."results_tab" to "service_role";

grant update on table "public"."results_tab" to "service_role";

grant delete on table "public"."resume_uploads" to "anon";

grant insert on table "public"."resume_uploads" to "anon";

grant references on table "public"."resume_uploads" to "anon";

grant select on table "public"."resume_uploads" to "anon";

grant trigger on table "public"."resume_uploads" to "anon";

grant truncate on table "public"."resume_uploads" to "anon";

grant update on table "public"."resume_uploads" to "anon";

grant delete on table "public"."resume_uploads" to "authenticated";

grant insert on table "public"."resume_uploads" to "authenticated";

grant references on table "public"."resume_uploads" to "authenticated";

grant select on table "public"."resume_uploads" to "authenticated";

grant trigger on table "public"."resume_uploads" to "authenticated";

grant truncate on table "public"."resume_uploads" to "authenticated";

grant update on table "public"."resume_uploads" to "authenticated";

grant delete on table "public"."resume_uploads" to "service_role";

grant insert on table "public"."resume_uploads" to "service_role";

grant references on table "public"."resume_uploads" to "service_role";

grant select on table "public"."resume_uploads" to "service_role";

grant trigger on table "public"."resume_uploads" to "service_role";

grant truncate on table "public"."resume_uploads" to "service_role";

grant update on table "public"."resume_uploads" to "service_role";

grant delete on table "public"."resumes" to "anon";

grant insert on table "public"."resumes" to "anon";

grant references on table "public"."resumes" to "anon";

grant select on table "public"."resumes" to "anon";

grant trigger on table "public"."resumes" to "anon";

grant truncate on table "public"."resumes" to "anon";

grant update on table "public"."resumes" to "anon";

grant delete on table "public"."resumes" to "authenticated";

grant insert on table "public"."resumes" to "authenticated";

grant references on table "public"."resumes" to "authenticated";

grant select on table "public"."resumes" to "authenticated";

grant trigger on table "public"."resumes" to "authenticated";

grant truncate on table "public"."resumes" to "authenticated";

grant update on table "public"."resumes" to "authenticated";

grant delete on table "public"."resumes" to "service_role";

grant insert on table "public"."resumes" to "service_role";

grant references on table "public"."resumes" to "service_role";

grant select on table "public"."resumes" to "service_role";

grant trigger on table "public"."resumes" to "service_role";

grant truncate on table "public"."resumes" to "service_role";

grant update on table "public"."resumes" to "service_role";

grant delete on table "public"."zip_archives" to "anon";

grant insert on table "public"."zip_archives" to "anon";

grant references on table "public"."zip_archives" to "anon";

grant select on table "public"."zip_archives" to "anon";

grant trigger on table "public"."zip_archives" to "anon";

grant truncate on table "public"."zip_archives" to "anon";

grant update on table "public"."zip_archives" to "anon";

grant delete on table "public"."zip_archives" to "authenticated";

grant insert on table "public"."zip_archives" to "authenticated";

grant references on table "public"."zip_archives" to "authenticated";

grant select on table "public"."zip_archives" to "authenticated";

grant trigger on table "public"."zip_archives" to "authenticated";

grant truncate on table "public"."zip_archives" to "authenticated";

grant update on table "public"."zip_archives" to "authenticated";

grant delete on table "public"."zip_archives" to "service_role";

grant insert on table "public"."zip_archives" to "service_role";

grant references on table "public"."zip_archives" to "service_role";

grant select on table "public"."zip_archives" to "service_role";

grant trigger on table "public"."zip_archives" to "service_role";

grant truncate on table "public"."zip_archives" to "service_role";

grant update on table "public"."zip_archives" to "service_role";


  create policy "Enable delete for authenticated users only"
  on "public"."accepted_matches"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."accepted_matches"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authed users"
  on "public"."accepted_matches"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."jobs"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read for authenticated users only"
  on "public"."jobs"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."projects"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for authed users"
  on "public"."projects"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable read access authenticated usesrs"
  on "public"."results"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."results_tab"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable select for authenticated users only"
  on "public"."results_tab"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable update for authenticated users only"
  on "public"."results_tab"
  as permissive
  for update
  to authenticated
using (true)
with check (true);



  create policy "Enable insert for authenticated users only"
  on "public"."resumes"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "allow select"
  on "public"."resumes"
  as permissive
  for select
  to authenticated
using (true);


CREATE TRIGGER "orchestrator-ingest-projects" AFTER INSERT ON public.project_uploads FOR EACH ROW EXECUTE FUNCTION public.notify_orchestrator_secure('https://heliochromic-isenthalpic-aidyn.ngrok-free.dev/ingest/projects');

CREATE TRIGGER "orchestrator-ingest-interns-individual" AFTER INSERT ON public.resume_uploads FOR EACH ROW EXECUTE FUNCTION public.notify_orchestrator_secure('https://heliochromic-isenthalpic-aidyn.ngrok-free.dev/ingest/interns/individual');

CREATE TRIGGER "orchestrator-injest-resumes-batch" AFTER INSERT ON public.zip_archives FOR EACH ROW EXECUTE FUNCTION public.notify_orchestrator_secure('https://heliochromic-isenthalpic-aidyn.ngrok-free.dev/ingest/interns/batch');


  create policy "Enable insert for authenticated users only"
  on "storage"."buckets"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable insert for authenticated users only"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (true);


CREATE TRIGGER on_project_delete AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.handle_project_deletion();

CREATE TRIGGER on_project_upload AFTER INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.handle_new_project_upload();

CREATE TRIGGER on_resume_delete AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.handle_resume_deletion();

CREATE TRIGGER on_resume_upload AFTER INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.handle_new_resume_upload();

CREATE TRIGGER on_zip_delete AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.handle_zip_deletion();

CREATE TRIGGER on_zip_upload AFTER INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION public.handle_new_zip_upload();


